language: go

go:
  - "1.11"

install:
  - mkdir /tmp/work
  - cd /tmp/work
  - go mod init example.com/m
  - go get github.com/gopherjs/gopherwasm@master
  - GO111MODULE=off go get github.com/gopherjs/gopherjs/...
  - GO111MODULE=off go get github.com/gopherjs/gopherwasm/...

script:
  - cd /tmp/wpork
  - GOOS=js GOARCH=wasm go test github.com/gopherjs/gopherwasm/...
  - gopherjs github.com/gopherjs/gopherjs/...
