language: go

sudo: false

go:
  - "1.11"

install:
  - nvm install node
  - nvm use node
  - mkdir /tmp/work
  - cd /tmp/work
  - go mod init example.com/m
  - go get github.com/gopherjs/gopherwasm@master
  - GO111MODULE=off go get github.com/gopherjs/gopherjs/...
  - GO111MODULE=off go get github.com/gopherjs/gopherwasm/...
  - export PATH=$(go env GOROOT)/misc/wasm:$PATH

script:
  - cd /tmp/work
  - GOOS=js GOARCH=wasm go test github.com/gopherjs/gopherwasm/js/...
  - gopherjs test github.com/gopherjs/gopherjs/js/...
